name: JK_Portfolio
favicon: null
layout_spectrum: 0.8423
typography_spectrum: 0.72905
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2dfcc'
    - '#3d505f'
    - '#73959e'
    - '#181611'
    - '#acabb0'
  brandStrength: 0.1875
  lightness: 0.6091468767262995
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
