name: JK_Portfolio
favicon: null
layout_spectrum: 0.57686
typography_spectrum: 0.72905
title: Jamie Keegan - Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2dfcc'
    - '#3d505f'
    - '#73959e'
    - '#181611'
    - '#acabb0'
  brandStrength: 0
  lightness: 0.6091468767262995
  saturation: 0.8689188435673714
  rhythmicContrast: 0.9744228962808847
purpose: []
